KLINE_MIN = 1
KLINE_5_MIN = 5 * KLINE_MIN
KLINE_15_MIN = 15 * KLINE_MIN
KLINE_30_MIN = 30 * KLINE_MIN
KLINE_HOUR = 60 * KLINE_MIN
KLINE_2_HOUR = 2 * KLINE_HOUR
KLINE_4_HOUR = 4 * KLINE_HOUR
KLINE_DAY = 24 * KLINE_HOUR
KLINE_WEEK = 7 * KLINE_DAY
KLINE_MONTH = 30 * KLINE_DAY
KLINE_YEAR = 365 * KLINE_DAY

PERIOD_TO_MS = 60 * 1000
